from playwright.sync_api import sync_playwright
import time


def test_addtobag(page):
    page.goto("https://www.google.com")
    # time.sleep(2)
    # page.get_by_title("Search").fill("Apple")
    page.get_by_role("combobox", name="Search").click()
    page.get_by_role("combobox", name="Search").fill("apple")
    page.keyboard.press("Enter")
    time.sleep(2)
    page.locator("//span[normalize-space()='Apple - Official Site']").click()
    time.sleep(3)
    page.get_by_role("link", name="iphone").first.click()
    time.sleep(4)
    page.locator(
        "//span[@conclass='chapternav-label'][normalize-space()='iPhone 13']").click()
    time.sleep(5)
    p = page.locator("input.form-label-small")
    p[1].click()
    # s = page.locator("span.row").all()
    # s[2].click()
    # page.locator("input[id='353d6830-a781-11ed-9455-d5bd9044a593']").click()
    # page.locator("(//span[@class='form-label-small'])[1]").click()
    time.sleep(4)
    k = page.locator("img.colornav-swatch").all()
    k[3].click()

    time.sleep(3)
    k = page.locator("span.row").all()
    k[4].click()
    time.sleep(2)
    page.get_by_text("No trade-in").click()
    time.sleep(3)
    page.locator("#applecareplus_59_noapplecare_label").click()
    time.sleep(5)
    # page.click('button:text("Add to Bag")')
    # time.sleep(4)
    page.get_by_role("button", name="Add to Bag").click()
    time.sleep(2)
    page.screenshot(path="..//data//screenshots//apple5.png")
    page.close()
